# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Magnetic_Cage_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import *
from ctypes import *
so_file = "/home/pi/Qt_GUI/GUI_C_Test.so"
my_functions = CDLL(so_file)

my_functions.setX.argtypes = [c_int]
my_functions.setY.argtypes = [c_int]
my_functions.setZ.argtypes = [c_int]
my_functions.setAcc.argtypes = [c_int]

my_functions.getTempX.argtypes = []
my_functions.getTempY.argtypes = []
my_functions.getTempZ.argtypes = []

my_functions.getCurrentX.argtypes = []
my_functions.getCurrentY.argtypes = []
my_functions.getCurrentZ.argtypes = []

my_functions.getMagFieldX.argtypes = []
my_functions.getMagFieldY.argtypes = []
my_functions.getMagFieldZ.argtypes = []

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Modes = QtWidgets.QTabWidget(self.centralwidget)
        self.Modes.setGeometry(QtCore.QRect(60, 30, 721, 341))
        self.Modes.setObjectName("Modes")
        self.CalibrateTab = QtWidgets.QWidget()
        self.CalibrateTab.setObjectName("CalibrateTab")
        self.Calibrate_Magnetic_Field_X = QtWidgets.QLineEdit(self.CalibrateTab)
        self.Calibrate_Magnetic_Field_X.setGeometry(QtCore.QRect(170, 20, 113, 32))
        self.Calibrate_Magnetic_Field_X.setObjectName("Calibrate_Magnetic_Field_X")
        self.Calibrate_Magnetic_Field_Y = QtWidgets.QLineEdit(self.CalibrateTab)
        self.Calibrate_Magnetic_Field_Y.setGeometry(QtCore.QRect(170, 60, 113, 32))
        self.Calibrate_Magnetic_Field_Y.setObjectName("Calibrate_Magnetic_Field_Y")
        self.Calibrate_Magnetic_Field_Z = QtWidgets.QLineEdit(self.CalibrateTab)
        self.Calibrate_Magnetic_Field_Z.setGeometry(QtCore.QRect(170, 100, 113, 32))
        self.Calibrate_Magnetic_Field_Z.setObjectName("Calibrate_Magnetic_Field_Z")
        self.Calibrate_Accuracy = QtWidgets.QLineEdit(self.CalibrateTab)
        self.Calibrate_Accuracy.setGeometry(QtCore.QRect(170, 140, 113, 32))
        self.Calibrate_Accuracy.setObjectName("Calibrate_Accuracy")
        self.Calibrate_Mag_X_Label = QtWidgets.QLabel(self.CalibrateTab)
        self.Calibrate_Mag_X_Label.setGeometry(QtCore.QRect(10, 20, 151, 22))
        self.Calibrate_Mag_X_Label.setObjectName("Calibrate_Mag_X_Label")
        self.Calibrate_Mag_Y_Label = QtWidgets.QLabel(self.CalibrateTab)
        self.Calibrate_Mag_Y_Label.setGeometry(QtCore.QRect(10, 60, 151, 22))
        self.Calibrate_Mag_Y_Label.setObjectName("Calibrate_Mag_Y_Label")
        self.Calibrate_Mag_Z_Label = QtWidgets.QLabel(self.CalibrateTab)
        self.Calibrate_Mag_Z_Label.setGeometry(QtCore.QRect(10, 100, 151, 22))
        self.Calibrate_Mag_Z_Label.setObjectName("Calibrate_Mag_Z_Label")
        self.Calibrate_Acc_Label = QtWidgets.QLabel(self.CalibrateTab)
        self.Calibrate_Acc_Label.setGeometry(QtCore.QRect(10, 140, 121, 22))
        self.Calibrate_Acc_Label.setObjectName("Calibrate_Acc_Label")
        self.Calibrate_Run = QtWidgets.QPushButton(self.CalibrateTab)
        self.Calibrate_Run.setGeometry(QtCore.QRect(70, 220, 99, 30))
        self.Calibrate_Run.setObjectName("Calibrate_Run")
        self.Calibrate_Run.clicked.connect(self.Calibratebtnstate)
        
        self.Calibrate_Stop = QtWidgets.QPushButton(self.CalibrateTab)
        self.Calibrate_Stop.setGeometry(QtCore.QRect(200, 220, 99, 30))
        self.Calibrate_Stop.setObjectName("Calibrate_Stop")
        self.Calibrate_Stop.clicked.connect(self.Stopbtnstate)
                
        self.CalibrateFrame = QtWidgets.QFrame(self.CalibrateTab)
        self.CalibrateFrame.setGeometry(QtCore.QRect(310, 20, 401, 231))
        self.CalibrateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CalibrateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CalibrateFrame.setObjectName("CalibrateFrame")
        self.label = QtWidgets.QLabel(self.CalibrateFrame)
        self.label.setGeometry(QtCore.QRect(10, 50, 68, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.CalibrateFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 68, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.CalibrateFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 68, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.CalibrateFrame)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 121, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.CalibrateFrame)
        self.label_5.setGeometry(QtCore.QRect(180, 10, 81, 22))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.CalibrateFrame)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 141, 22))
        self.label_6.setObjectName("label_6")
        self.Calibrate_Temp_X = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Temp_X.setGeometry(QtCore.QRect(80, 50, 71, 31))
        self.Calibrate_Temp_X.setReadOnly(True)
        self.Calibrate_Temp_X.setObjectName("Calibrate_Temp_X")
        self.Calibrate_Temp_Y = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Temp_Y.setGeometry(QtCore.QRect(80, 100, 71, 31))
        self.Calibrate_Temp_Y.setReadOnly(True)
        self.Calibrate_Temp_Y.setObjectName("Calibrate_Temp_Y")
        self.Calibrate_Temp_Z = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Temp_Z.setGeometry(QtCore.QRect(80, 150, 71, 31))
        self.Calibrate_Temp_Z.setReadOnly(True)
        self.Calibrate_Temp_Z.setObjectName("Calibrate_Temp_Z")
        self.Calibrate_Current_X = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Current_X.setGeometry(QtCore.QRect(180, 50, 71, 31))
        self.Calibrate_Current_X.setReadOnly(True)
        self.Calibrate_Current_X.setObjectName("Calibrate_Current_X")
        self.Calibrate_MagField_X = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_MagField_X.setGeometry(QtCore.QRect(290, 50, 71, 31))
        self.Calibrate_MagField_X.setReadOnly(True)
        self.Calibrate_MagField_X.setObjectName("Calibrate_MagField_X")
        self.Calibrate_Current_Y = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Current_Y.setGeometry(QtCore.QRect(180, 100, 71, 31))
        self.Calibrate_Current_Y.setReadOnly(True)
        self.Calibrate_Current_Y.setObjectName("Calibrate_Current_Y")
        self.Calibrate_Current_Z = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_Current_Z.setGeometry(QtCore.QRect(180, 150, 71, 31))
        self.Calibrate_Current_Z.setReadOnly(True)
        self.Calibrate_Current_Z.setObjectName("Calibrate_Current_Z")
        self.Calibrate_MagField_Y = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_MagField_Y.setGeometry(QtCore.QRect(290, 100, 71, 31))
        self.Calibrate_MagField_Y.setReadOnly(True)
        self.Calibrate_MagField_Y.setObjectName("Calibrate_MagField_Y")
        self.Calibrate_MagField_Z = QtWidgets.QLineEdit(self.CalibrateFrame)
        self.Calibrate_MagField_Z.setGeometry(QtCore.QRect(290, 150, 71, 31))
        self.Calibrate_MagField_Z.setReadOnly(True)
        self.Calibrate_MagField_Z.setObjectName("Calibrate_MagField_Z")
        self.Modes.addTab(self.CalibrateTab, "")
        self.StaticTab = QtWidgets.QWidget()
        self.StaticTab.setObjectName("StaticTab")
        self.Static_Magnetic_Field_X = QtWidgets.QLineEdit(self.StaticTab)
        self.Static_Magnetic_Field_X.setGeometry(QtCore.QRect(170, 20, 113, 32))
        self.Static_Magnetic_Field_X.setObjectName("Static_Magnetic_Field_X")
        self.Static_Magnetic_Field_Y = QtWidgets.QLineEdit(self.StaticTab)
        self.Static_Magnetic_Field_Y.setGeometry(QtCore.QRect(170, 60, 113, 32))
        self.Static_Magnetic_Field_Y.setObjectName("Static_Magnetic_Field_Y")
        self.Static_Magnetic_Field_Z = QtWidgets.QLineEdit(self.StaticTab)
        self.Static_Magnetic_Field_Z.setGeometry(QtCore.QRect(170, 100, 113, 32))
        self.Static_Magnetic_Field_Z.setObjectName("Static_Magnetic_Field_Z")
        self.Static_Accuracy = QtWidgets.QLineEdit(self.StaticTab)
        self.Static_Accuracy.setGeometry(QtCore.QRect(170, 140, 113, 32))
        self.Static_Accuracy.setObjectName("Static_Accuracy")
        self.Static_Mag_X_Label = QtWidgets.QLabel(self.StaticTab)
        self.Static_Mag_X_Label.setGeometry(QtCore.QRect(10, 20, 151, 22))
        self.Static_Mag_X_Label.setObjectName("Static_Mag_X_Label")
        self.Static_Mag_Y_Label = QtWidgets.QLabel(self.StaticTab)
        self.Static_Mag_Y_Label.setGeometry(QtCore.QRect(10, 60, 151, 22))
        self.Static_Mag_Y_Label.setObjectName("Static_Mag_Y_Label")
        self.Static_Mag_Z_Label = QtWidgets.QLabel(self.StaticTab)
        self.Static_Mag_Z_Label.setGeometry(QtCore.QRect(10, 100, 151, 22))
        self.Static_Mag_Z_Label.setObjectName("Static_Mag_Z_Label")
        self.Static_Acc_Label = QtWidgets.QLabel(self.StaticTab)
        self.Static_Acc_Label.setGeometry(QtCore.QRect(10, 140, 121, 22))
        self.Static_Acc_Label.setObjectName("Static_Acc_Label")
        self.Static_Run = QtWidgets.QPushButton(self.StaticTab)
        self.Static_Run.setGeometry(QtCore.QRect(70, 220, 99, 30))
        self.Static_Run.setObjectName("Static_Run")
        self.Static_Run.clicked.connect(self.Staticbtnstate)

        self.Static_Stop = QtWidgets.QPushButton(self.StaticTab)
        self.Static_Stop.setGeometry(QtCore.QRect(200, 220, 99, 30))
        self.Static_Stop.setObjectName("Static_Stop")
        self.Static_Stop.clicked.connect(self.Stopbtnstate)

        self.CalibrateFrame_2 = QtWidgets.QFrame(self.StaticTab)
        self.CalibrateFrame_2.setGeometry(QtCore.QRect(310, 20, 401, 231))
        self.CalibrateFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CalibrateFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CalibrateFrame_2.setObjectName("CalibrateFrame_2")
        self.label_7 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 68, 22))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 68, 22))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 68, 22))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_10.setGeometry(QtCore.QRect(60, 10, 121, 22))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_11.setGeometry(QtCore.QRect(180, 10, 81, 22))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.CalibrateFrame_2)
        self.label_12.setGeometry(QtCore.QRect(260, 10, 141, 22))
        self.label_12.setObjectName("label_12")
        self.Static_Temp_X = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Temp_X.setGeometry(QtCore.QRect(80, 50, 71, 31))
        self.Static_Temp_X.setReadOnly(True)
        self.Static_Temp_X.setObjectName("Static_Temp_X")
        self.Static_Temp_Y = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Temp_Y.setGeometry(QtCore.QRect(80, 100, 71, 31))
        self.Static_Temp_Y.setReadOnly(True)
        self.Static_Temp_Y.setObjectName("Static_Temp_Y")
        self.Static_Temp_Z = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Temp_Z.setGeometry(QtCore.QRect(80, 150, 71, 31))
        self.Static_Temp_Z.setReadOnly(True)
        self.Static_Temp_Z.setObjectName("Static_Temp_Z")
        self.Static_Current_X = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Current_X.setGeometry(QtCore.QRect(180, 50, 71, 31))
        self.Static_Current_X.setReadOnly(True)
        self.Static_Current_X.setObjectName("Static_Current_X")
        self.Static_MagField_X = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_MagField_X.setGeometry(QtCore.QRect(290, 50, 71, 31))
        self.Static_MagField_X.setReadOnly(True)
        self.Static_MagField_X.setObjectName("Static_MagField_X")
        self.Static_Current_Y = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Current_Y.setGeometry(QtCore.QRect(180, 100, 71, 31))
        self.Static_Current_Y.setReadOnly(True)
        self.Static_Current_Y.setObjectName("Static_Current_Y")
        self.Static_Current_Z = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_Current_Z.setGeometry(QtCore.QRect(180, 150, 71, 31))
        self.Static_Current_Z.setReadOnly(True)
        self.Static_Current_Z.setObjectName("Static_Current_Z")
        self.Static_MagField_Y = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_MagField_Y.setGeometry(QtCore.QRect(290, 100, 71, 31))
        self.Static_MagField_Y.setReadOnly(True)
        self.Static_MagField_Y.setObjectName("Static_MagField_Y")
        self.Static_MagField_Z = QtWidgets.QLineEdit(self.CalibrateFrame_2)
        self.Static_MagField_Z.setGeometry(QtCore.QRect(290, 150, 71, 31))
        self.Static_MagField_Z.setReadOnly(True)
        self.Static_MagField_Z.setObjectName("Static_MagField_Z")
        self.Modes.addTab(self.StaticTab, "")
        self.DynamicTab = QtWidgets.QWidget()
        self.DynamicTab.setObjectName("DynamicTab")
        self.Dynamic_Run = QtWidgets.QPushButton(self.DynamicTab)
        self.Dynamic_Run.setGeometry(QtCore.QRect(70, 220, 99, 30))
        self.Dynamic_Run.setObjectName("Dynamic_Run")
        self.Dynamic_Run.clicked.connect(self.Dynamicbtnstate)

        self.Dynamic_Stop = QtWidgets.QPushButton(self.DynamicTab)
        self.Dynamic_Stop.setGeometry(QtCore.QRect(200, 220, 99, 30))
        self.Dynamic_Stop.setObjectName("Dynamic_Stop")
        self.Dynamic_Stop.clicked.connect(self.Stopbtnstate)
                
        self.DynamicFileSelect = QtWidgets.QPushButton(self.DynamicTab)
        self.DynamicFileSelect.setGeometry(QtCore.QRect(130, 100, 99, 30))
        self.DynamicFileSelect.setObjectName("DynamicFileSelect")
        self.DynamicFileSelect.clicked.connect(self.FileSelect)
        
        self.CalibrateFrame_3 = QtWidgets.QFrame(self.DynamicTab)
        self.CalibrateFrame_3.setGeometry(QtCore.QRect(310, 20, 401, 231))
        self.CalibrateFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CalibrateFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CalibrateFrame_3.setObjectName("CalibrateFrame_3")
        self.label_13 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 68, 22))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 68, 22))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_15.setGeometry(QtCore.QRect(10, 150, 68, 22))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_16.setGeometry(QtCore.QRect(60, 10, 121, 22))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_17.setGeometry(QtCore.QRect(180, 10, 81, 22))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.CalibrateFrame_3)
        self.label_18.setGeometry(QtCore.QRect(260, 10, 141, 22))
        self.label_18.setObjectName("label_18")
        self.Dynamic_Temp_X = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Temp_X.setGeometry(QtCore.QRect(80, 50, 71, 31))
        self.Dynamic_Temp_X.setReadOnly(True)
        self.Dynamic_Temp_X.setObjectName("Dynamic_Temp_X")
        self.Dynamic_Temp_Y = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Temp_Y.setGeometry(QtCore.QRect(80, 100, 71, 31))
        self.Dynamic_Temp_Y.setReadOnly(True)
        self.Dynamic_Temp_Y.setObjectName("Dynamic_Temp_Y")
        self.Dynamic_Temp_Z = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Temp_Z.setGeometry(QtCore.QRect(80, 150, 71, 31))
        self.Dynamic_Temp_Z.setReadOnly(True)
        self.Dynamic_Temp_Z.setObjectName("Dynamic_Temp_Z")
        self.Dynamic_Current_X = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Current_X.setGeometry(QtCore.QRect(180, 50, 71, 31))
        self.Dynamic_Current_X.setReadOnly(True)
        self.Dynamic_Current_X.setObjectName("Dynamic_Current_X")
        self.Dynamic_MagField_X = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_MagField_X.setGeometry(QtCore.QRect(290, 50, 71, 31))
        self.Dynamic_MagField_X.setReadOnly(True)
        self.Dynamic_MagField_X.setObjectName("Dynamic_MagField_X")
        self.Dynamic_Current_Y = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Current_Y.setGeometry(QtCore.QRect(180, 100, 71, 31))
        self.Dynamic_Current_Y.setReadOnly(True)
        self.Dynamic_Current_Y.setObjectName("Dynamic_Current_Y")
        self.Dynamic_Current_Z = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_Current_Z.setGeometry(QtCore.QRect(180, 150, 71, 31))
        self.Dynamic_Current_Z.setReadOnly(True)
        self.Dynamic_Current_Z.setObjectName("Dynamic_Current_Z")
        self.Dynamic_MagField_Y = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_MagField_Y.setGeometry(QtCore.QRect(290, 100, 71, 31))
        self.Dynamic_MagField_Y.setReadOnly(True)
        self.Dynamic_MagField_Y.setObjectName("Dynamic_MagField_Y")
        self.Dynamic_MagField_Z = QtWidgets.QLineEdit(self.CalibrateFrame_3)
        self.Dynamic_MagField_Z.setGeometry(QtCore.QRect(290, 150, 71, 31))
        self.Dynamic_MagField_Z.setReadOnly(True)
        self.Dynamic_MagField_Z.setObjectName("Dynamic_MagField_Z")
        self.Modes.addTab(self.DynamicTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Modes.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.DisplayUpdate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Calibrate_Mag_X_Label.setText(_translate("MainWindow", "Magnetic Field X (nT)"))
        self.Calibrate_Mag_Y_Label.setText(_translate("MainWindow", "Magnetic Field Y (nT)"))
        self.Calibrate_Mag_Z_Label.setText(_translate("MainWindow", "Magnetic Field Z (nT)"))
        self.Calibrate_Acc_Label.setText(_translate("MainWindow", "Accuracy (%)"))
        self.Calibrate_Run.setText(_translate("MainWindow", "Run"))
        self.Calibrate_Stop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "X-Axis:"))
        self.label_2.setText(_translate("MainWindow", "Y-Axis:"))
        self.label_3.setText(_translate("MainWindow", "Z-Axis:"))
        self.label_4.setText(_translate("MainWindow", "Temperature (C)"))
        self.label_5.setText(_translate("MainWindow", "Current (A)"))
        self.label_6.setText(_translate("MainWindow", "Magnetic Field (nT)"))
        self.Modes.setTabText(self.Modes.indexOf(self.CalibrateTab), _translate("MainWindow", "Calibrate"))
        self.Static_Mag_X_Label.setText(_translate("MainWindow", "Magnetic Field X (nT)"))
        self.Static_Mag_Y_Label.setText(_translate("MainWindow", "Magnetic Field Y (nT)"))
        self.Static_Mag_Z_Label.setText(_translate("MainWindow", "Magnetic Field Z (nT)"))
        self.Static_Acc_Label.setText(_translate("MainWindow", "Accuracy (%)"))
        self.Static_Run.setText(_translate("MainWindow", "Run"))
        self.Static_Stop.setText(_translate("MainWindow", "Stop"))
        self.label_7.setText(_translate("MainWindow", "X-Axis:"))
        self.label_8.setText(_translate("MainWindow", "Y-Axis:"))
        self.label_9.setText(_translate("MainWindow", "Z-Axis:"))
        self.label_10.setText(_translate("MainWindow", "Temperature (C)"))
        self.label_11.setText(_translate("MainWindow", "Current (A)"))
        self.label_12.setText(_translate("MainWindow", "Magnetic Field (nT)"))
        self.Modes.setTabText(self.Modes.indexOf(self.StaticTab), _translate("MainWindow", "Static"))
        self.Dynamic_Run.setText(_translate("MainWindow", "Run"))
        self.Dynamic_Stop.setText(_translate("MainWindow", "Stop"))
        self.DynamicFileSelect.setText(_translate("MainWindow", "Select File"))
        self.label_13.setText(_translate("MainWindow", "X-Axis:"))
        self.label_14.setText(_translate("MainWindow", "Y-Axis:"))
        self.label_15.setText(_translate("MainWindow", "Z-Axis:"))
        self.label_16.setText(_translate("MainWindow", "Temperature (C)"))
        self.label_17.setText(_translate("MainWindow", "Current (A)"))
        self.label_18.setText(_translate("MainWindow", "Magnetic Field (nT)"))
        self.Modes.setTabText(self.Modes.indexOf(self.DynamicTab), _translate("MainWindow", "Dynamic"))
        
    def DisplayUpdate(self):
        xT = my_functions.getTempX()
        yT = my_functions.getTempY()
        zT = my_functions.getTempZ()
        
        xC = my_functions.getCurrentX()
        yC = my_functions.getCurrentY()
        zC = my_functions.getCurrentZ()
        
        xB = my_functions.getMagFieldX()
        yB = my_functions.getMagFieldY()
        zB = my_functions.getMagFieldZ()
        
        self.Calibrate_Temp_X.setText(str(xT))
        self.Calibrate_Temp_Y.setText(str(yT))
        self.Calibrate_Temp_Z.setText(str(zT))
        self.Calibrate_Current_X.setText(str(xC))
        self.Calibrate_Current_Y.setText(str(yC))
        self.Calibrate_Current_Z.setText(str(zC))
        self.Calibrate_MagField_X.setText(str(xB))
        self.Calibrate_MagField_Y.setText(str(yB))
        self.Calibrate_MagField_Z.setText(str(zB))
        
        self.Static_Temp_X.setText(str(xT))
        self.Static_Temp_Y.setText(str(yT))
        self.Static_Temp_Z.setText(str(zT))
        self.Static_Current_X.setText(str(xC))
        self.Static_Current_Y.setText(str(yC))
        self.Static_Current_Z.setText(str(zC))
        self.Static_MagField_X.setText(str(xB))
        self.Static_MagField_Y.setText(str(yB))
        self.Static_MagField_Z.setText(str(zB))

        self.Dynamic_Temp_X.setText(str(xT))
        self.Dynamic_Temp_Y.setText(str(yT))
        self.Dynamic_Temp_Z.setText(str(zT))
        self.Dynamic_Current_X.setText(str(xC))
        self.Dynamic_Current_Y.setText(str(yC))
        self.Dynamic_Current_Z.setText(str(zC))
        self.Dynamic_MagField_X.setText(str(xB))
        self.Dynamic_MagField_Y.setText(str(yB))
        self.Dynamic_MagField_Z.setText(str(zB))
        
    
    def Calibratebtnstate(self):
        x = self.Calibrate_Magnetic_Field_X.text()
        y = self.Calibrate_Magnetic_Field_Y.text()
        z = self.Calibrate_Magnetic_Field_Z.text()
        acc = self.Calibrate_Accuracy.text()
        my_functions.setX(int(x))
        my_functions.setY(int(y))
        my_functions.setZ(int(z))
        my_functions.setAcc(int(acc))
        print(x)
        print(y)
        print(z)
        print(acc)
        self.timer.start(500)
        
    def Staticbtnstate(self):
        x = self.Static_Magnetic_Field_X.text()
        y = self.Static_Magnetic_Field_Y.text()
        z = self.Static_Magnetic_Field_Z.text()
        acc = self.Static_Accuracy.text()
        my_functions.setX(x)
        my_functions.setY(y)
        my_functions.setZ(z)
        my_functions.setAcc(acc)
        print(x)
        print(y)
        print(z)
        print(acc)
        self.timer.start(500)
        
    def Dynamicbtnstate(self):
        self.timer.start(500)
            
    def FileSelect(self):
        path = QFileDialog.getOpenFileName(self, "QFileDialog.getOpenFileName()", "", "CSV Files (*.csv)", options=QFileDialog.Options())
    
    def Stopbtnstate(self):
        self.timer.stop()
        
        self.Calibrate_Temp_X.clear()
        self.Calibrate_Temp_Y.clear()
        self.Calibrate_Temp_Z.clear()
        self.Static_Temp_X.clear()
        self.Static_Temp_Y.clear()
        self.Static_Temp_Z.clear()
        self.Dynamic_Temp_X.clear()
        self.Dynamic_Temp_Y.clear()
        self.Dynamic_Temp_Z.clear()
        
        self.Calibrate_Current_X.clear()
        self.Calibrate_Current_Y.clear()
        self.Calibrate_Current_Z.clear()
        self.Static_Current_X.clear()
        self.Static_Current_Y.clear()
        self.Static_Current_Z.clear()
        self.Dynamic_Current_X.clear()
        self.Dynamic_Current_Y.clear()
        self.Dynamic_Current_Z.clear()
        
        self.Calibrate_MagField_X.clear()
        self.Calibrate_MagField_Y.clear()
        self.Calibrate_MagField_Z.clear()
        self.Static_MagField_X.clear()
        self.Static_MagField_Y.clear()
        self.Static_MagField_Z.clear()
        self.Dynamic_MagField_X.clear()
        self.Dynamic_MagField_Y.clear()
        self.Dynamic_MagField_Z.clear()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

